FROM node:latest AS builder

WORKDIR /app
COPY ./config/package*.json ./

RUN npm install

FROM node:latest

WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY ./config/server.js .

EXPOSE {{ container_port }}

CMD ["node", "server.js"]
