FROM python:{{applications[application_id].version}}

# Install required packages including 'make'
RUN apt-get update && apt-get install -y make

# Set the working directory
WORKDIR {{docker_app_dir}}

# Copy the project files into the container
COPY {{host_cymais_volume_dir_relative}} {{docker_app_dir}}

# Install Python packages via requirements.txt
RUN cd {{docker_sphinx_dir}} && pip install --upgrade pip && pip install -r requirements.txt

# Build the HTML documentation using Sphinx with the defined directories
RUN cd {{docker_sphinx_dir}} && make html

# Expose port 8000 where the HTTP server will run
EXPOSE 8000

# Start a simple HTTP server to serve the built documentation
CMD ["python", "-m", "http.server", "8000", "--directory", "${BUILD_DIR}"]
