FROM wordpress

# Install msmtp and update system
RUN apt-get update && \
    apt-get install -y msmtp msmtp-mta && \
    rm -rf /var/lib/apt/lists/*

# Install WP CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

# Copy msmtp configuration and PHP upload settings
COPY config/msmtprc.conf /etc/msmtprc
COPY upload.ini $PHP_INI_DIR/conf.d/